### ISSUE TITLE
How about non issue commit?

### ISSUE THREAD

**Issue by unional** [conventional-changelog/conventionalcommits.org#16]
e.g commits for version bump, update dependencies, update readme etc?

Should they also consider as `fix`?

**Comment by stevemao** [comment]
> version bump, update dependencies

`chore`

> update readme

`docs`

Its not mentioned here?

**Comment by unional** [comment]
I see.

I have created a PR, IMO put it on the list make it easier to follow, as people would look for all types in the same section. 🌷

**Comment by jameswomack** [comment]
Echoing @stevemao, [Unleash](https://github.com/netflix/unleash) creates a [commit](https://github.com/Netflix/unleash/commit/d0d89ca7046cc0f33359e53fc78f2c22e1b6b827) with the format `chore(release): <insert release name here> <insert semantic version here>` for releases, e.g. `chore(release): release 1.6.1`. 

I've always used `chore` with a tag for those sorts of tasks because that's what the Angular team did, as well as the early conventional commit helper packages.

**Comment by daKmoR** [comment]
hmm a release is actually something big right?
so why is it not 
`RELEASE: 1.2.3`  ?
`chore(release): 1.2.3`  seems pretty small in comparison?

**Comment by stevemao** [comment]
@daKmoR I don't think I understand your question?

`chore(release): 1.2.3` is a great message for release. However for monorepo, since there's no single version, I use `chore(release): publish` (https://github.com/conventional-changelog/conventional-changelog/blob/master/package.json)

**Comment by zanona** [comment]
Hey guys, 
I have noticed that Angular convention no longer mentions about `chore`, it seems `refactor` would be the one being used in its place? and yet many places still use `chore`.
I know this is all optional and depends on personal/team opinion, but do you guys know why has it been replaced/disappeared and what is the best way to still tag trivial updates, like text changes in websites, or something that would work as a `feat` neither a `fix` and yet `refactor` is not the right word.

Thanks in advance.
